// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLeoviOTXrSx-33DuESh1km929l9Voyq8',
    appId: '1:426044845240:web:9c0f7b15efd585007ad84d',
    messagingSenderId: '426044845240',
    projectId: 'music-app-ae021',
    authDomain: 'music-app-ae021.firebaseapp.com',
    databaseURL: 'https://music-app-ae021-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'music-app-ae021.firebasestorage.app',
    measurementId: 'G-ZT1CEWHYMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiO1bGQUxyhuJTTP_SIsI-vuXEuJrk-mg',
    appId: '1:426044845240:android:53b608885d8f48cb7ad84d',
    messagingSenderId: '426044845240',
    projectId: 'music-app-ae021',
    databaseURL: 'https://music-app-ae021-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'music-app-ae021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw6aDd_0JiAVMRf_jqO9w5ztKLTenvdns',
    appId: '1:426044845240:ios:49fbb7c5d72ab0a27ad84d',
    messagingSenderId: '426044845240',
    projectId: 'music-app-ae021',
    databaseURL: 'https://music-app-ae021-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'music-app-ae021.firebasestorage.app',
    iosBundleId: 'com.example.soundclubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw6aDd_0JiAVMRf_jqO9w5ztKLTenvdns',
    appId: '1:426044845240:ios:49fbb7c5d72ab0a27ad84d',
    messagingSenderId: '426044845240',
    projectId: 'music-app-ae021',
    databaseURL: 'https://music-app-ae021-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'music-app-ae021.firebasestorage.app',
    iosBundleId: 'com.example.soundclubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLeoviOTXrSx-33DuESh1km929l9Voyq8',
    appId: '1:426044845240:web:e32e945ed1bb8b217ad84d',
    messagingSenderId: '426044845240',
    projectId: 'music-app-ae021',
    authDomain: 'music-app-ae021.firebaseapp.com',
    databaseURL: 'https://music-app-ae021-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'music-app-ae021.firebasestorage.app',
    measurementId: 'G-Z31MVVWGX4',
  );

}